packages:
  - 'apps/*'
  - 'packages/*'
  - 'server'
allowBuilds:
  better-sqlite3: true
  cpu-features: true
  electron: true
  esbuild: true
  protobufjs: true
  sharp: true
  ssh2: true
  unrs-resolver: true
