/**
 * Types for the Karpathy-style automatic learning loop.
 *
 * This module defines the core data structures used throughout the loop:
 * - LoopIteration: Represents a single iteration of the learning loop
 * - LoopReport: Summary report of all iterations
 * - ScheduleConfig: Configuration for overnight/scheduled execution
 */

/**
 * Represents a single iteration of the learning loop.
 */
export interface LoopIteration {
  /** The iteration number (1-based) */
  iteration: number;

  /** The LLM-generated proposal for improvement */
  proposal: string;

  /** The generated patch/code changes */
  patch: string;

  /** Result of running tests on the patch */
  testResult: TestResult;

  /** Whether this iteration was committed (passed tests and showed improvement) */
  committed: boolean;

  /** Numeric improvement score (positive = better, negative = worse) */
  improvement: number;
}

/**
 * Result of running tests on a patch.
 */
export interface TestResult {
  /** Whether all tests passed */
  passed: boolean;

  /** Error message if tests failed */
  error?: string;

  /** Test output/logs */
  output?: string;

  /** Time taken to run tests (ms) */
  duration: number;
}

/**
 * Summary report of all iterations in a learning loop run.
 */
export interface LoopReport {
  /** Total number of iterations attempted */
  totalIterations: number;

  /** Number of iterations that were committed */
  committedCount: number;

  /** Number of iterations that were rolled back */
  rolledBackCount: number;

  /** Sum of all improvement scores */
  totalImprovement: number;

  /** Detailed information about each iteration */
  iterations: LoopIteration[];
}

/**
 * Configuration for scheduled/overnight execution.
 */
export interface ScheduleConfig {
  /** Whether scheduling is enabled */
  enabled: boolean;

  /** ISO string of when to start execution */
  startTime: string;

  /** Maximum number of iterations to run (default: 20) */
  maxIterations: number;

  /** Cooldown between iterations in minutes */
  cooldownMinutes: number;
}

/**
 * Options for configuring the KarpathyLoop.
 */
export interface LoopOptions {
  /** Maximum iterations (default: 20) */
  maxIterations?: number;

  /** Improvement threshold for committing (default: 0.1) */
  improvementThreshold?: number;

  /** Path to the codebase being improved */
  codebasePath: string;

  /** LLM model to use for generation */
  model?: string;

  /** Callback for logging iteration progress */
  onIteration?: (iteration: LoopIteration) => void;
}

/**
 * Proposal generated by the LLM for code improvement.
 */
export interface Proposal {
  /** Description of the proposed change */
  description: string;

  /** Target file(s) to modify */
  targets: string[];

  /** Expected improvement */
  expectedImprovement: number;
}

/**
 * Patch generated by the LLM.
 */
export interface CodePatch {
  /** The file path to patch */
  filePath: string;

  /** The new code content (full replacement) */
  content: string;

  /** Description of the change */
  description: string;
}
